import { Exercise } from '../types';

export const EXERCISES: Exercise[] = [
  {
    id: 'squat',
    name: 'Back Squat',
    category: 'lower_body',
    muscles_primary: ['Quadriceps', 'Glutes'],
    muscles_secondary: ['Hamstrings', 'Core', 'Calves'],
    equipment_required: ['barbell'],
    difficulty: 'intermediate',
    setup_cues: [
      'Bar sits on upper traps, not your neck',
      'Feet shoulder-width apart, toes slightly out (15-30°)',
      'Brace core before unracking',
    ],
    execution_cues: [
      'Push knees out in line with toes as you descend',
      'Break at hips and knees simultaneously',
      'Aim for thighs parallel or below',
      'Drive through full foot to stand',
    ],
    common_mistakes: [
      'Knees caving inward',
      'Heels rising off floor',
      'Forward torso lean (chest falls)',
      'Not reaching depth',
    ],
    contraindications: ['knees', 'lower_back', 'hips'],
  },
  {
    id: 'goblet_squat',
    name: 'Goblet Squat',
    category: 'lower_body',
    muscles_primary: ['Quadriceps', 'Glutes'],
    muscles_secondary: ['Core', 'Upper Back'],
    equipment_required: ['dumbbell', 'kettlebell'],
    difficulty: 'beginner',
    setup_cues: [
      'Hold dumbbell vertically at chest height',
      'Feet shoulder-width, toes out slightly',
    ],
    execution_cues: [
      'Elbows inside knees at the bottom',
      'Keep chest tall throughout',
      'Drive through heels to stand',
    ],
    common_mistakes: ['Letting elbows push knees in', 'Rounding upper back'],
    contraindications: ['knees'],
  },
  {
    id: 'deadlift',
    name: 'Conventional Deadlift',
    category: 'posterior_chain',
    muscles_primary: ['Hamstrings', 'Glutes', 'Erectors'],
    muscles_secondary: ['Traps', 'Lats', 'Core'],
    equipment_required: ['barbell'],
    difficulty: 'intermediate',
    setup_cues: [
      'Bar over mid-foot, about 1 inch from shins',
      'Hip-width stance, toes forward or slightly out',
      'Hinge at hips to grip just outside legs',
      'Shoulders slightly in front of bar',
    ],
    execution_cues: [
      'Push floor away, don\'t think "pull"',
      'Bar stays in contact with legs the whole way',
      'Lock out hips at the top — don\'t hyperextend',
      'Hinge back to lower, then bend knees',
    ],
    common_mistakes: [
      'Bar drifting away from body',
      'Rounding lower back',
      'Jerking the bar off the floor',
      'Hyperextending at lockout',
    ],
    contraindications: ['lower_back'],
  },
  {
    id: 'rdl',
    name: 'Romanian Deadlift',
    category: 'posterior_chain',
    muscles_primary: ['Hamstrings', 'Glutes'],
    muscles_secondary: ['Erectors', 'Core'],
    equipment_required: ['barbell', 'dumbbell'],
    difficulty: 'intermediate',
    setup_cues: [
      'Stand with bar at hip level',
      'Soft bend in knees throughout',
      'Shoulder-width stance',
    ],
    execution_cues: [
      'Push hips back while keeping bar close to legs',
      'Feel stretch in hamstrings — stop before rounding',
      'Drive hips forward to stand',
    ],
    common_mistakes: ['Bending knees too much (becomes a squat)', 'Rounding back'],
    contraindications: ['lower_back', 'hamstrings'],
  },
  {
    id: 'bench_press',
    name: 'Barbell Bench Press',
    category: 'upper_push',
    muscles_primary: ['Chest', 'Anterior Deltoids'],
    muscles_secondary: ['Triceps', 'Serratus'],
    equipment_required: ['barbell', 'bench'],
    difficulty: 'intermediate',
    setup_cues: [
      'Eyes under the bar before unracking',
      'Grip slightly wider than shoulder-width',
      'Feet flat, slight arch in lower back',
      'Retract and depress shoulder blades',
    ],
    execution_cues: [
      'Lower to lower chest with control (~2 seconds)',
      'Flare elbows to about 45-75°',
      'Press in a slight arc back toward the rack',
    ],
    common_mistakes: ['Bouncing off chest', 'Flaring elbows 90°', 'Losing back arch under load'],
    contraindications: ['shoulders', 'wrists', 'elbows'],
  },
  {
    id: 'push_up',
    name: 'Push-Up',
    category: 'upper_push',
    muscles_primary: ['Chest', 'Anterior Deltoids'],
    muscles_secondary: ['Triceps', 'Core'],
    equipment_required: [],
    difficulty: 'beginner',
    setup_cues: [
      'Hands slightly wider than shoulders',
      'Body in a straight line from head to heels',
      'Fingers spread, index finger pointing forward',
    ],
    execution_cues: [
      'Lower until chest nearly touches floor',
      'Elbows at roughly 45° to body',
      'Press fully to lock out at top',
    ],
    common_mistakes: ['Hips sagging or piking', 'Partial range of motion', 'Flaring elbows wide'],
    contraindications: ['wrists', 'shoulders', 'elbows'],
  },
  {
    id: 'overhead_press',
    name: 'Overhead Press',
    category: 'upper_push',
    muscles_primary: ['Deltoids'],
    muscles_secondary: ['Triceps', 'Upper Traps', 'Core'],
    equipment_required: ['barbell', 'dumbbell'],
    difficulty: 'intermediate',
    setup_cues: [
      'Bar at upper chest, hands just outside shoulders',
      'Elbows slightly forward of bar',
      'Brace core hard before pressing',
    ],
    execution_cues: [
      'Press straight up, move head back slightly as bar passes face',
      'Lock out overhead, shrug at top',
      'Control the descent back to starting position',
    ],
    common_mistakes: ['Leaning back excessively', 'Using leg drive when not intended', 'Not locking out'],
    contraindications: ['shoulders', 'neck', 'wrists'],
  },
  {
    id: 'pull_up',
    name: 'Pull-Up',
    category: 'upper_pull',
    muscles_primary: ['Lats', 'Biceps'],
    muscles_secondary: ['Rear Delts', 'Core', 'Rhomboids'],
    equipment_required: ['pull_up_bar'],
    difficulty: 'intermediate',
    setup_cues: [
      'Grip slightly wider than shoulder-width, overhand',
      'Dead hang to start, shoulders packed',
    ],
    execution_cues: [
      'Initiate with shoulder blades, then pull elbows to hips',
      'Chin over bar at the top',
      'Lower with control to full hang',
    ],
    common_mistakes: ['Kipping without intent', 'Not achieving full range', 'Shrugging shoulders up'],
    contraindications: ['shoulders', 'elbows', 'wrists'],
  },
  {
    id: 'bent_over_row',
    name: 'Barbell Bent-Over Row',
    category: 'upper_pull',
    muscles_primary: ['Lats', 'Rhomboids', 'Mid Traps'],
    muscles_secondary: ['Biceps', 'Rear Delts', 'Erectors'],
    equipment_required: ['barbell'],
    difficulty: 'intermediate',
    setup_cues: [
      'Hinge to torso ~45° or more parallel to floor',
      'Grip slightly wider than shoulder-width',
      'Back flat, knees soft',
    ],
    execution_cues: [
      'Pull bar toward lower chest/upper abdomen',
      'Lead with elbows, keep them close to body',
      'Squeeze shoulder blades at the top',
    ],
    common_mistakes: ['Using too much momentum', 'Letting hips rise to meet bar', 'Partial reps'],
    contraindications: ['lower_back'],
  },
  {
    id: 'dumbbell_row',
    name: 'Single-Arm Dumbbell Row',
    category: 'upper_pull',
    muscles_primary: ['Lats', 'Rhomboids'],
    muscles_secondary: ['Biceps', 'Rear Delts'],
    equipment_required: ['dumbbell', 'bench'],
    difficulty: 'beginner',
    setup_cues: [
      'Brace on bench with same-side hand and knee',
      'Back flat and parallel to floor',
    ],
    execution_cues: [
      'Pull dumbbell to hip, elbow skims close to body',
      'Full stretch at bottom',
      'Avoid rotating torso to gain range',
    ],
    common_mistakes: ['Rotating torso', 'Partial range of motion'],
    contraindications: ['lower_back', 'shoulders'],
  },
  {
    id: 'lunge',
    name: 'Walking Lunge',
    category: 'lower_body',
    muscles_primary: ['Quadriceps', 'Glutes'],
    muscles_secondary: ['Hamstrings', 'Core'],
    equipment_required: [],
    difficulty: 'beginner',
    setup_cues: ['Stand tall, core braced', 'Hold dumbbells at sides if adding weight'],
    execution_cues: [
      'Step forward, lower back knee toward floor',
      'Front knee stays behind toes',
      'Push through front heel to step forward',
    ],
    common_mistakes: ['Front knee caving in', 'Leaning forward excessively'],
    contraindications: ['knees', 'hips'],
  },
  {
    id: 'hip_thrust',
    name: 'Hip Thrust',
    category: 'lower_body',
    muscles_primary: ['Glutes'],
    muscles_secondary: ['Hamstrings', 'Core'],
    equipment_required: ['barbell', 'bench'],
    difficulty: 'intermediate',
    setup_cues: [
      'Upper back on bench, bar over hip crease',
      'Feet hip-width, knees bent ~90° at top',
    ],
    execution_cues: [
      'Drive hips up by squeezing glutes',
      'At top: body from shoulders to knees is level',
      'Hold a second at the top, control down',
    ],
    common_mistakes: ['Arching lower back instead of driving hips', 'Not reaching full hip extension'],
    contraindications: ['lower_back', 'hips'],
  },
  {
    id: 'glute_bridge',
    name: 'Glute Bridge',
    category: 'lower_body',
    muscles_primary: ['Glutes'],
    muscles_secondary: ['Hamstrings', 'Core'],
    equipment_required: [],
    difficulty: 'beginner',
    setup_cues: ['Lie on back, feet flat on floor hip-width apart', 'Arms by sides'],
    execution_cues: [
      'Press through heels and squeeze glutes to lift hips',
      'Body forms a straight line from knees to shoulders',
      'Hold 1-2 seconds, lower with control',
    ],
    common_mistakes: ['Using lower back instead of glutes', 'Not fully extending hips'],
    contraindications: ['lower_back'],
  },
  {
    id: 'plank',
    name: 'Plank',
    category: 'core',
    muscles_primary: ['Core', 'Transverse Abdominis'],
    muscles_secondary: ['Shoulders', 'Glutes'],
    equipment_required: [],
    difficulty: 'beginner',
    setup_cues: [
      'Forearms on floor, elbows under shoulders',
      'Toes on floor, body in straight line',
    ],
    execution_cues: [
      'Squeeze glutes and brace abs throughout',
      'Don\'t let hips sag or pike',
      'Breathe steadily',
    ],
    common_mistakes: ['Hips too high or low', 'Holding breath', 'Neck forward'],
    contraindications: ['wrists', 'shoulders'],
  },
  {
    id: 'deadbug',
    name: 'Dead Bug',
    category: 'core',
    muscles_primary: ['Core', 'Transverse Abdominis'],
    muscles_secondary: ['Hip Flexors'],
    equipment_required: [],
    difficulty: 'beginner',
    setup_cues: ['Lie on back, arms straight up, hips and knees at 90°', 'Press lower back into floor'],
    execution_cues: [
      'Slowly extend opposite arm and leg toward floor',
      'Keep lower back pressed to floor throughout',
      'Return and switch sides',
    ],
    common_mistakes: ['Letting lower back arch off floor', 'Moving too fast'],
    contraindications: ['lower_back'],
  },
  {
    id: 'pallof_press',
    name: 'Pallof Press',
    category: 'core',
    muscles_primary: ['Obliques', 'Core'],
    muscles_secondary: ['Shoulders'],
    equipment_required: ['cable_machine', 'resistance_band'],
    difficulty: 'intermediate',
    setup_cues: [
      'Stand sideways to cable/band, feet shoulder-width',
      'Hold at chest, resist rotation',
    ],
    execution_cues: [
      'Press hands away from chest, resist any rotation',
      'Hold extended for 2 seconds',
      'Return to chest with control',
    ],
    common_mistakes: ['Allowing torso to rotate', 'Using momentum'],
    contraindications: [],
  },
  {
    id: 'face_pull',
    name: 'Face Pull',
    category: 'upper_pull',
    muscles_primary: ['Rear Deltoids', 'External Rotators'],
    muscles_secondary: ['Mid Traps', 'Rhomboids'],
    equipment_required: ['cable_machine', 'resistance_band'],
    difficulty: 'beginner',
    setup_cues: ['Cable/band at face height', 'Overhand grip on rope, knuckles facing up'],
    execution_cues: [
      'Pull toward face, elbows flare high',
      'End position: hands by ears, elbows back',
      'Control the return',
    ],
    common_mistakes: ['Elbows too low', 'Using too much weight (biceps dominate)'],
    contraindications: ['shoulders', 'elbows'],
  },
  {
    id: 'bulgarian_split_squat',
    name: 'Bulgarian Split Squat',
    category: 'lower_body',
    muscles_primary: ['Quadriceps', 'Glutes'],
    muscles_secondary: ['Hamstrings', 'Core'],
    equipment_required: ['bench'],
    difficulty: 'intermediate',
    setup_cues: [
      'Rear foot on bench, front foot far enough that torso stays vertical',
      'Hold dumbbells at sides',
    ],
    execution_cues: [
      'Lower straight down, front knee tracks over toes',
      'Keep torso upright throughout',
      'Drive through front heel to stand',
    ],
    common_mistakes: ['Front knee caving in', 'Leaning forward', 'Back knee hitting floor hard'],
    contraindications: ['knees', 'hips', 'ankles'],
  },
  {
    id: 'lat_pulldown',
    name: 'Lat Pulldown',
    category: 'upper_pull',
    muscles_primary: ['Lats'],
    muscles_secondary: ['Biceps', 'Rear Delts'],
    equipment_required: ['cable_machine'],
    difficulty: 'beginner',
    setup_cues: ['Wide overhand grip, slight lean back', 'Legs secured under pads'],
    execution_cues: [
      'Pull bar to upper chest, leading with elbows',
      'Squeeze lats at the bottom',
      'Slow controlled return to straight arms',
    ],
    common_mistakes: ['Pulling behind neck', 'Using momentum/swinging'],
    contraindications: ['shoulders', 'neck'],
  },
  {
    id: 'tricep_dip',
    name: 'Tricep Dip',
    category: 'upper_push',
    muscles_primary: ['Triceps'],
    muscles_secondary: ['Chest', 'Anterior Deltoids'],
    equipment_required: ['bench'],
    difficulty: 'beginner',
    setup_cues: ['Hands on bench behind you, feet forward', 'Hips just off edge of bench'],
    execution_cues: [
      'Lower until elbows at ~90°',
      'Keep back close to bench',
      'Press back up to straight arms',
    ],
    common_mistakes: ['Flaring elbows out', 'Leaning too far forward'],
    contraindications: ['shoulders', 'wrists', 'elbows'],
  },
  {
    id: 'bicep_curl',
    name: 'Dumbbell Bicep Curl',
    category: 'upper_pull',
    muscles_primary: ['Biceps'],
    muscles_secondary: ['Forearms'],
    equipment_required: ['dumbbell'],
    difficulty: 'beginner',
    setup_cues: ['Stand tall, dumbbells at sides, palms forward', 'Elbows pinned to sides'],
    execution_cues: [
      'Curl both dumbbells to shoulder height',
      'Squeeze biceps at the top',
      'Lower with control — 2-3 seconds',
    ],
    common_mistakes: ['Swinging body to get weight up', 'Elbows drifting forward'],
    contraindications: ['elbows', 'wrists'],
  },
  {
    id: 'lateral_raise',
    name: 'Lateral Raise',
    category: 'upper_push',
    muscles_primary: ['Lateral Deltoids'],
    muscles_secondary: ['Traps'],
    equipment_required: ['dumbbell'],
    difficulty: 'beginner',
    setup_cues: ['Stand tall, light dumbbells at sides', 'Slight bend in elbows'],
    execution_cues: [
      'Raise arms to shoulder height, leading with elbows',
      'Tilt dumbbells so pinky is slightly higher',
      'Lower with 3-second control',
    ],
    common_mistakes: ['Using too much weight / swinging', 'Shrugging traps up'],
    contraindications: ['shoulders'],
  },
  {
    id: 'calf_raise',
    name: 'Calf Raise',
    category: 'lower_body',
    muscles_primary: ['Gastrocnemius', 'Soleus'],
    muscles_secondary: [],
    equipment_required: [],
    difficulty: 'beginner',
    setup_cues: ['Stand on edge of step or flat floor', 'Hold something for balance if needed'],
    execution_cues: [
      'Rise onto toes as high as possible',
      'Hold peak 1 second',
      'Lower all the way down for full stretch',
    ],
    common_mistakes: ['Partial range of motion', 'Bouncing'],
    contraindications: ['ankles'],
  },
  {
    id: 'mountain_climber',
    name: 'Mountain Climber',
    category: 'cardio',
    muscles_primary: ['Core', 'Hip Flexors'],
    muscles_secondary: ['Shoulders', 'Chest'],
    equipment_required: [],
    difficulty: 'beginner',
    setup_cues: ['Push-up position, hands under shoulders', 'Core braced, hips level'],
    execution_cues: [
      'Drive one knee toward chest, then quickly switch',
      'Keep hips level — don\'t let them pike or sag',
      'Move at a controlled but brisk pace',
    ],
    common_mistakes: ['Hips rising up', 'Losing plank position'],
    contraindications: ['wrists', 'shoulders'],
  },
  {
    id: 'jumping_jack',
    name: 'Jumping Jack',
    category: 'cardio',
    muscles_primary: ['Full Body'],
    muscles_secondary: [],
    equipment_required: [],
    difficulty: 'beginner',
    setup_cues: ['Stand tall, feet together, arms at sides'],
    execution_cues: [
      'Jump feet out wide as arms rise overhead',
      'Jump back to start simultaneously',
      'Land softly with slightly bent knees',
    ],
    common_mistakes: ['Locking out knees on landing', 'Rushing'],
    contraindications: ['ankles', 'knees'],
  },
  {
    id: 'box_jump',
    name: 'Box Jump',
    category: 'power',
    muscles_primary: ['Glutes', 'Quadriceps'],
    muscles_secondary: ['Calves', 'Core'],
    equipment_required: ['box'],
    difficulty: 'intermediate',
    setup_cues: ['Stand arm\'s length from box', 'Athletic stance, slight hinge'],
    execution_cues: [
      'Swing arms and explode through hips',
      'Land softly on top, absorb with bend in knees',
      'Step down — don\'t jump down',
    ],
    common_mistakes: ['Landing stiff-legged', 'Jumping down instead of stepping'],
    contraindications: ['knees', 'ankles'],
  },
  {
    id: 'row_machine',
    name: 'Rowing Machine',
    category: 'cardio',
    muscles_primary: ['Full Body'],
    muscles_secondary: [],
    equipment_required: ['cardio_rower'],
    difficulty: 'beginner',
    setup_cues: ['Feet strapped in, damper at 3-5', 'Grip overhand, arms extended, slight forward lean'],
    execution_cues: [
      'Drive through legs first',
      'Then lean back to 11 o\'clock',
      'Then pull handle to lower chest',
      'Return: arms, body, legs in reverse',
    ],
    common_mistakes: ['Pulling with arms first', 'Hunching back'],
    contraindications: ['lower_back'],
  },
  {
    id: 'band_pull_apart',
    name: 'Band Pull-Apart',
    category: 'upper_pull',
    muscles_primary: ['Rear Deltoids', 'Mid Traps'],
    muscles_secondary: ['Rhomboids'],
    equipment_required: ['resistance_band'],
    difficulty: 'beginner',
    setup_cues: ['Hold band at shoulder width, arms straight', 'Slight tension in the band'],
    execution_cues: [
      'Pull band apart to stretch it across chest',
      'Squeeze shoulder blades at full stretch',
      'Return with control',
    ],
    common_mistakes: ['Bending elbows', 'Shrugging shoulders'],
    contraindications: ['shoulders', 'elbows'],
  },
  {
    id: 'kb_swing',
    name: 'Kettlebell Swing',
    category: 'power',
    muscles_primary: ['Glutes', 'Hamstrings'],
    muscles_secondary: ['Core', 'Shoulders'],
    equipment_required: ['kettlebell'],
    difficulty: 'intermediate',
    setup_cues: ['KB on floor, stand behind it', 'Hike KB back between legs like a hike snap'],
    execution_cues: [
      'Drive hips forward explosively — this powers the swing',
      'Arms guide the bell, they don\'t lift it',
      'At top, body fully extended, glutes squeezed',
      'Let bell fall, hinge back, repeat',
    ],
    common_mistakes: ['Squatting instead of hinging', 'Arms lifting the bell', 'Rounding back'],
    contraindications: ['lower_back', 'shoulders'],
  },
];

export const getExerciseById = (id: string): Exercise | undefined =>
  EXERCISES.find((e) => e.id === id);

export const getExercisesByEquipment = (equipment: string[]): Exercise[] =>
  EXERCISES.filter((e) =>
    e.equipment_required.length === 0 ||
    e.equipment_required.some((eq) => equipment.includes(eq))
  );

export const getExercisesForMuscle = (muscle: string): Exercise[] =>
  EXERCISES.filter(
    (e) =>
      e.muscles_primary.includes(muscle) || e.muscles_secondary.includes(muscle)
  );
